//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MapEditor.rc
//
#define IDC_ShowStaticPL                1020
#define IDC_ShowDynamicPL               1021
#define IDC_ShowFog                     1022
#define IDD_MAPOBJDLG                   7000
#define IDC_BUTTON_Add                  7000
#define IDC_objList                     7001
#define IDD_SelAtt                      7001
#define IDD_EDITDLG                     7002
#define IDC_STATIC_hwndDraw             7003
#define IDD_DIALOG_SETWEATHER           7004
#define IDC_Load                        7005
#define IDD_WayPoint                    7005
#define IDC_Save                        7006
#define IDD_FilterSelect                7006
#define IDC_COMBO1                      7007
#define IDC_objTypeList                 7007
#define IDC_COMBO_SPRING                7007
#define IDC_CHECK_Select                7008
#define IDC_CHECK_Follow                7008
#define IDC_CHECK_COPY_ADD              7008
#define IDC_COMBO_SUMMER                7008
#define IDD_ConfigFile                  7008
#define IDD_MapProperty                 7008
#define IDC_EDIT1                       7009
#define IDC_EDIT_MAPID                  7009
#define IDC_MAPID                       7009
#define IDC_COMBO_AUTUMN                7009
#define IDC_FREQ                        7009
#define IDC_EDIT2                       7010
#define IDC_EDIT_ATTID                  7010
#define IDC_EDIT_WAYPOINTNAME           7010
#define IDC_COMBO_WINTER                7010
#define IDD_DIALOG_Adaptive             7010
#define IDC_EDIT_OffX                   7010
#define IDC_SCALE                       7010
#define IDC_EDIT3                       7011
#define IDC_EDIT_XPOS                   7011
#define IDC_EDIT_TIMEZONE               7011
#define IDB_BITMAP1                     7011
#define IDC_X                           7011
#define IDC_EDIT4                       7012
#define IDC_EDIT_YPOS                   7012
#define IDC_EDIT_MAZEZONERADIUS         7012
#define IDD_ResourceGather              7012
#define IDC_EDIT_SUNPOSY                7012
#define IDC_Y                           7012
#define IDC_EDIT5                       7013
#define IDC_EDIT_ZPOS                   7013
#define IDC_EDIT_CITYNAME               7013
#define IDC_Z                           7013
#define IDC_EDIT6                       7014
#define IDC_EDIT_DIR                    7014
#define IDC_EDIT_SUNPOSZ                7014
#define IDC_OK                          7015
#define IDC_EDIT_DUNGEON                7015
#define IDC_EDIT_InstanceTime           7015
#define IDR_ACCELERATOR1                7015
#define IDC_BUTTON2                     7016
#define IDC_CANCEL                      7016
#define IDC_BUTTON_NEWMAP               7016
#define IDC_BUTTON_ECHOCOL              7016
#define IDD_CLOULD                      7016
#define IDC_EDIT_SPEED                  7017
#define IDC_EDIT_InstanceTime2          7017
#define IDC_BUTTON_DynamicDiff          7017
#define IDC_CHECK_LockSelected          7019
#define IDC_propList                    7020
#define IDC_BUTTON_DynamicAmb           7020
#define IDC_Commit                      7021
#define IDC_BUTTON_DynamicDiff3         7021
#define IDC_BUTTON_DynamicSpec          7021
#define IDC_Ad                          7022
#define IDC_Adaptive                    7022
#define IDC_LIST1                       7023
#define IDC_AttList                     7023
#define IDC_CannotMount                 7023
#define IDC_CannotTransmit              7024
#define IDC_CHECK1                      7026
#define IDC_CHECK_PICKWAYPOINT          7026
#define IDC_CHECK_MAZEZONE              7026
#define IDC_CHECK_MAPRECT               7026
#define IDC_CHECK_FOLLOWMOVE            7026
#define IDC_CHECK_RenderSkyShade        7026
#define IDD_DIALOG_CHOPFIELDTYPE        7027
#define IDC_COMBOBOX_CHOPFIELDTYPE      7028
#define IDC_BUTTON_Weather              7029
#define IDC_MapAtt                      7032
#define IDC_Delete                      7032
#define IDC_BUTTON_SUNCOL               7032
#define IDC_ADD                         7032
#define IDC_FindRoleByWayPoint          7033
#define IDC_ComboRepu                   7034
#define IDC_Instance                    7035
#define IDC_CHECK_NPC                   7037
#define IDC_CHECK_Monster               7038
#define IDC_CHECK_DynamicBlock          7038
#define IDC_CHECK_StaticObj             7039
#define IDC_CHECK_MazeWall              7040
#define IDC_CHECK_Quad                  7041
#define IDC_EDIT_Tag                    7042
#define IDC_CollectList                 7043
#define IDC_BUTTON_CopyAdd              7044
#define IDC_BUTTON_Filter               7045
#define IDC_BnAdative                   7046
#define IDC_ObjLock                     7047
#define IDC_CHECK3                      7048
#define IDC_ObjFlag                     7048
#define IDC_NewAdd                      7049
#define IDC_Read                        7050
#define IDC_BUTTON3                     7051
#define IDC_BUTTON_ResGather            7051
#define IDC_BUTTON_Specular             7051
#define IDC_EDIT_SUNPOSX                7052
#define IDC_EDIT_SUNCOLOR               7053
#define IDC_EDIT_ECHOCOL                7054
#define IDC_EDIT9                       7054
#define IDC_EDIT_ZSIZE                  7054
#define IDC_BTN_TOP                     7059
#define IDC_BTN_FNTRGT                  7060
#define IDC_BTN_BCKLEFT                 7061
#define IDC_EDIT_XSIZE                  7062
#define IDC_EDIT_YSIZE                  7063
#define IDC_EDIT10                      7064
#define IDC_EDIT11                      7065
#define IDC_EDIT12                      7066
#define IDC_EDIT_OffY                   7067
#define IDC_EDIT_OffZ                   7068
#define IDC_EDIT_Modulus                7069
#define IDC_EDIT7                       7070
#define IDC_BUTTON_FogColor             7071
#define IDC_EDIT_FogDensity             7072
#define IDC_EDIT13                      7073
#define IDC_EDIT_FogStart               7073
#define IDC_EDIT8                       7074
#define IDC_EDIT_FogEnd                 7074
#define IDC_EDIT_FogEnd2                7075
#define IDC_EDIT_Dist                   7075
#define IDC_CHECK2_Trigger              7075
#define IDC_CHECK4_WayPoint             7076
#define IDC_BUTTON4_SkyCol              7077
#define IDC_BUTTON4_SkyCol2             7078
#define IDC_SkyShadeCol                 7078
#define IDC_BTNAddCol_Top               7080
#define IDC_BUTTON6                     7081
#define IDC_BTNAddCol_Bottom            7081
#define IDC_CHECK2                      7082
#define IDC_CHECK_Door                  7082
#define IDC_CHECK_TriggerEffect         7083
#define IDC_CLOUD                       7085
#define IDC_LAYERS                      7086
#define IDC_DEL                         7087
#define IDC_LAYERPROP                   7088
#define IDC_APPLY                       7089
#define IDC_BUTTON1                     7090
#define IDC_EXPORT                      7090

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        7017
#define _APS_NEXT_COMMAND_VALUE         32782
#define _APS_NEXT_CONTROL_VALUE         7091
#define _APS_NEXT_SYMED_VALUE           7003
#endif
#endif
