#pragma once

template <class T>
class CProxy_IHtmLanchEvents : public IConnectionPointImpl<T, &__uuidof(_IHtmLanchEvents), CComDynamicUnkArray>
{
	//Warning this class will  be regenerated by the wizard.
public:
};
